In [1]:
import statsmodels.api as sm
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

In [2]:
df_cleaned = pd.read_csv('data/listings_cleaned.csv', low_memory=False)
df_cleaned.head()

,id,price,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,bed_type,...,instant_bookable,is_business_travel_ready,cancellation_policy,host_is_superhost,listing_url,cleaning_fee,security_deposit,extra_people,guests_included,region
0,2265,225.0,30.27750,-97.71398,House,Entire home/apt,4,2.0,2.0,Real Bed,...,f,f,strict_14_with_grace_period,t,https://www.airbnb.com/rooms/2265,100.0,500.0,30.0,4,East
1,5245,100.0,30.27577,-97.71379,House,Private room,2,1.0,1.0,Real Bed,...,f,f,strict_14_with_grace_period,t,https://www.airbnb.com/rooms/5245,75.0,500.0,35.0,2,East
2,5456,95.0,30.26112,-97.73448,Guesthouse,Entire home/apt,3,1.0,1.0,Real Bed,...,f,f,strict_14_with_grace_period,t,https://www.airbnb.com/rooms/5456,0.0,100.0,45.0,2,East
3,5769,40.0,30.45697,-97.78422,House,Private room,2,1.0,1.0,Real Bed,...,f,f,moderate,t,https://www.airbnb.com/rooms/5769,0.0,0.0,0.0,2,North
4,6413,99.0,30.24829,-97.73726,Guesthouse,Entire home/apt,2,1.0,1.0,Real Bed,...,t,f,strict_14_with_grace_period,t,https://www.airbnb.com/rooms/6413,50.0,0.0,25.0,2,South

In [3]:
df_cleaned.drop(['amenities', 'cancellation_policy','instant_bookable', 'listing_url','bed_type', 
                 'review_scores_rating', 'guests_included']
                #, 'property_type','accommodates', ,'is_business_travel_ready','host_is_superhost', ]#], 
                ,axis=1, inplace=True)

In [4]:
categorical = df_cleaned.select_dtypes(include='object').columns
categorical

Index(['property_type', 'room_type', 'is_business_travel_ready',
       'host_is_superhost', 'region'],
      dtype='object')

In [5]:
# Create dummy variables for categorical columns in the df
df_cleaned = pd.get_dummies(df_cleaned, drop_first=True)
df_cleaned.head()

,id,price,latitude,longitude,accommodates,bathrooms,bedrooms,minimum_nights,number_of_reviews,availability_365,...,property_type_Serviced apartment,property_type_Townhouse,room_type_Hotel room,room_type_Private room,room_type_Shared room,host_is_superhost_t,region_East,region_North,region_South,region_West
0,2265,225.0,30.27750,-97.71398,4,2.0,2.0,30,24,0,...,0,0,0,0,0,1,1,0,0,0
1,5245,100.0,30.27577,-97.71379,2,1.0,1.0,30,9,0,...,0,0,0,1,0,1,1,0,0,0
2,5456,95.0,30.26112,-97.73448,3,1.0,1.0,2,529,334,...,0,0,0,0,0,1,1,0,0,0
3,5769,40.0,30.45697,-97.78422,2,1.0,1.0,1,257,14,...,0,0,0,1,0,1,0,1,0,0
4,6413,99.0,30.24829,-97.73726,2,1.0,1.0,3,112,0,...,0,0,0,0,0,1,0,0,1,0

In [6]:
numerical = df_cleaned.select_dtypes(include=['int64', 'float']).drop(['price', 'latitude', 'longitude'], axis=1).columns
numerical

Index(['id', 'accommodates', 'bathrooms', 'bedrooms', 'minimum_nights',
       'number_of_reviews', 'availability_365', 'cleaning_fee',
       'security_deposit', 'extra_people'],
      dtype='object')

In [7]:
scaler = StandardScaler()
df_scaled = df_cleaned.copy()
df_scaled[numerical] = scaler.fit_transform(df_scaled[numerical])

In [8]:
X = df_cleaned.drop(['price', 'id'], axis=1)
y = np.log(df_cleaned[['price']])

X.drop(['property_type_Bungalow', 'property_type_Guesthouse', 'property_type_House', 'property_type_Serviced apartment',
       'region_West'], axis=1, inplace=True)

X.shape

(11541, 23)

In [9]:
X = sm.add_constant(X)

ols_model = sm.OLS(y, X.astype(float))
res = ols_model.fit()
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.511
Model:                            OLS   Adj. R-squared:                  0.510
Method:                 Least Squares   F-statistic:                     523.3
Date:                Wed, 05 Aug 2020   Prob (F-statistic):               0.00
Time:                        13:40:15   Log-Likelihood:                -11535.
No. Observations:               11541   AIC:                         2.312e+04
Df Residuals:                   11517   BIC:                         2.329e+04
Df Model:                          23
Covariance Type:            nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                        66.8917     14.138      4.731      0.000      39.179      94.605
latitude                     -0.5597      0.180     -3.101      0.002      -0.913      -0.206
longitude                     0.4645      0.134      3.471      0.001       0.202       0.727
accommodates                  0.0480      0.004     12.744      0.000       0.041       0.055
bathrooms                     0.2039      0.014     14.319      0.000       0.176       0.232
bedrooms                      0.1293      0.013     10.226      0.000       0.105       0.154
minimum_nights               -0.0039      0.000     -9.946      0.000      -0.005      -0.003
number_of_reviews            -0.0015      0.000    -13.892      0.000      -0.002      -0.001
availability_365              0.0004   4.91e-05      8.245      0.000       0.000       0.001
cleaning_fee                  0.0008      0.000      7.370      0.000       0.001       0.001
security_deposit              0.0001   1.45e-05      7.245      0.000    7.68e-05       0.000
extra_people                  0.0007      0.000      2.994      0.003       0.000       0.001
property_type_Condominium    -0.0862      0.022     -3.918      0.000      -0.129      -0.043
property_type_Guest suite    -0.1812      0.042     -4.360      0.000      -0.263      -0.100
property_type_Loft            0.2710      0.057      4.765      0.000       0.160       0.382
property_type_Other           0.1619      0.030      5.360      0.000       0.103       0.221
property_type_Townhouse      -0.1100      0.033     -3.293      0.001      -0.175      -0.044
room_type_Hotel room         -0.3715      0.097     -3.816      0.000      -0.562      -0.181
room_type_Private room       -0.5903      0.017    -35.015      0.000      -0.623      -0.557
room_type_Shared room        -1.2745      0.054    -23.471      0.000      -1.381      -1.168
host_is_superhost_t          -0.2021      0.015    -13.896      0.000      -0.231      -0.174
region_East                  -0.1651      0.019     -8.814      0.000      -0.202      -0.128
region_North                 -0.3589      0.032    -11.194      0.000      -0.422      -0.296
region_South                 -0.0863      0.020     -4.215      0.000      -0.126      -0.046
==============================================================================
Omnibus:                     1004.045   Durbin-Watson:                   1.622
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1589.312
Skew:                           0.659   Prob(JB):                         0.00
Kurtosis:                       4.252   Cond. No.                     1.20e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.2e+06. This might indicate that there are
strong multicollinearity or other numerical problems.